### PR TITLE
Include superclass class loaders when defining subclass mocks

### LINKED ISSUE #2694: java.lang.NoClassDefFoundError with mockito 3.11+
Hi, we found following issue in our projects after updating mockito from 3.6 to 4.3.

Example: We have four different Java classes in four different OSGi plug-ins. In OSGi, each plug-ins has its own classloader.

Plug-in 1 contains the interface:

`public interface IDummyObject { }`

Plug-in 2 contains an implementation and has a dependency, e.g. here to org.eclipse.emf.ecore:

```
import org.eclipse.emf.ecore.EObject;

import dummyInterfaces.IDummyObject;

public class DummyObject implements IDummyObject {
  EObject _obj;
}
```

Plug-in 3 contains an other implementation, here it is a subclass of DummyObject and implemented as a component. The plug-in has no dependency to org.eclipse.emf.ecore:

```
import org.osgi.service.component.annotations.Component;

import dummyInterfaces.IDummyObject;

@Component
public class ExtendedDummyObject extends DummyObject implements IDummyObject {

}
```

Plug-In 4 contains a test using a spy on the injected dummy object:

```
import static org.mockito.Mockito.spy;

import javax.inject.Inject;

import org.junit.jupiter.api.Test;

import dummyInterfaces.IDummyObject;
import vi.testfw.ITest;

public class DummyObjectTest implements ITest {

  @Inject
  private IDummyObject _dummyObject;

  @Test
  void testSomething() {
    spy(_dummyObject);
  }

}
```

With the update from mockito 3.10 to 3.11 following change was comitted: [https://github.com/mockito/mockito/commit/66998ea7f81c6adf49983cea081586e19760b7a0](https://github.com/mockito/mockito/commit/66998ea7f81c6adf49983cea081586e19760b7a0), containing following change: `.appendMostSpecific(getAllTypes(features.mockedType))` changed to `.appendMostSpecific(features.mockedType)
`

Scenario above used to work before. Also the commit message says "This should **only** affect cases that previously would have thrown an exception." However, with this commit the classloader of the superclass DummyObject is not fetched anymore, only the classloaders for the interface IDummyObject and the ExtendedDummyObject, leading to following exception:

```
java.lang.NoClassDefFoundError: org/eclipse/emf/ecore/EObject
	at org.mockito.codegen.ExtendedDummyObject$MockitoMock$91908986.<clinit>(Unknown Source)
	at jdk.internal.reflect.GeneratedSerializationConstructorAccessor10.newInstance(Unknown Source)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.objenesis.instantiator.sun.SunReflectionFactoryInstantiator.newInstance(SunReflectionFactoryInstantiator.java:48)
	at org.objenesis.ObjenesisBase.newInstance(ObjenesisBase.java:73)
	at org.mockito.internal.creation.instance.ObjenesisInstantiator.newInstance(ObjenesisInstantiator.java:22)
	at org.mockito.internal.creation.bytebuddy.SubclassByteBuddyMockMaker.createMock(SubclassByteBuddyMockMaker.java:48)
	at org.mockito.internal.creation.bytebuddy.ByteBuddyMockMaker.createMock(ByteBuddyMockMaker.java:42)
	at org.mockito.internal.util.MockUtil.lambda$createMock$0(MockUtil.java:48)
	at java.base/java.util.Optional.orElseGet(Optional.java:369)
	at org.mockito.internal.util.MockUtil.createMock(MockUtil.java:46)
	at org.mockito.internal.MockitoCore.mock(MockitoCore.java:96)
	at org.mockito.Mockito.spy(Mockito.java:2048)
	at dummyPackage.DummyObjectTest.setUp(DummyObjectTest.java:26)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:725)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.api.extension.InvocationInterceptor.interceptBeforeEachMethod(InvocationInterceptor.java:103)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptLifecycleMethod(TimeoutExtension.java:126)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptBeforeEachMethod(TimeoutExtension.java:76)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeMethodInExtensionContext(ClassBasedTestDescriptor.java:506)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$synthesizeBeforeEachMethodAdapter$21(ClassBasedTestDescriptor.java:491)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeBeforeEachMethods$3(TestMethodTestDescriptor.java:171)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeBeforeMethodsOrCallbacksUntilExceptionOccurs$6(TestMethodTestDescriptor.java:199)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeBeforeMethodsOrCallbacksUntilExceptionOccurs(TestMethodTestDescriptor.java:199)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeBeforeEachMethods(TestMethodTestDescriptor.java:168)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:131)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:66)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:107)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:95)
	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:91)
	at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:60)
	at org.eclipse.jdt.internal.junit5.runner.JUnit5TestReference.run(JUnit5TestReference.java:98)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:542)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:770)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:464)
	at org.eclipse.pde.internal.junit.runtime.RemotePluginTestRunner.main(RemotePluginTestRunner.java:171)
	at org.eclipse.pde.internal.junit.runtime.CoreTestApplication.run(CoreTestApplication.java:27)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.internal.app.EclipseAppContainer.callMethodWithException(EclipseAppContainer.java:593)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:205)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:657)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:594)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1457)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1420)
Caused by: java.lang.ClassNotFoundException: org.eclipse.emf.ecore.EObject
	at java.base/java.lang.ClassLoader.findClass(ClassLoader.java:719)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at net.bytebuddy.dynamic.loading.MultipleParentClassLoader.loadClass(MultipleParentClassLoader.java:131)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 110 more
```

### PR DESCRIPTION
**Pull request by Develop-KIM**
Fixes #2694.

### Problem

Since 3.11 (#2306 / 66998ea), the subclass mock maker builds the mock's class loader from the mocked type's own class loader only — `appendMostSpecific(getAllTypes(features.mockedType))` became `appendMostSpecific(features.mockedType)`.

When the mocked type's superclass lives in a different class loader (e.g. a separate OSGi bundle) and exposes a type that only that loader can see, the generated mock's class loader can no longer reach it, so loading/using the mock fails with `NoClassDefFoundError` for that type — as in the original report.

### Fix

Collect the mocked type and its superclasses again, so the mock's class loader reaches the defining loader of every supertype. `MultipleParentClassLoader.Builder.appendMostSpecific` removes any loader that is a parent of another within the set, so when all supertypes share one class loader (the common, non-OSGi case) the result collapses back to that single loader — no overhead for default usage.

### Test

Adds an OSGi regression test in the `osgi-tests` subproject with three bundles:

- `depBundle` — owns `ForeignType`
- `otherBundle` — a superclass exposing `ForeignType` (imports `depBundle`)
- `testBundle` — a subclass of that superclass (does **not** import `depBundle`) plus the test

Without the fix the test fails with `NoClassDefFoundError: org/mockito/osgitest/depbundle/ForeignType`; with the fix it passes. The full `mockito-core` test suite and the `osgi-tests` suite pass locally.

---

This change was written with AI assistance (disclosed in the commit trailer); I've reviewed it and can explain every line.

### CODE REVIEW

**Comment by jselbo** [comment]
I'd like to defer to @raphw on this one for review.

**Comment by raphw** [comment]
I'm on vacation but will visit this ticket in August.

**Comment by raphw** [comment]
We removed this to avoid that many types become (partially) unmockable. With multiple class loaders, we need to generate an additional class loader, and loose access to package-private classes. Any public type that is referenced from a super class loader must be exported to the instance class loader anyways, or this would be a bug in the OSGi referencing.

**Comment by Develop-KIM** [comment]
That's fair, and I don't want to trade package-private mocking away for this.

On the OSGi point though, I think the wiring in the repro is legal. The test bundle extends a class from another bundle, doesn't override `foreignType()`, and never touches `ForeignType` — so it has no reason to import that package. Plain reflection agrees: `SubClassInTestBundle.class.getMethods()` resolves the inherited method through the declaring class' loader, which is the other bundle, and works. What breaks is the generated mock, because it redeclares every overridable method — `ForeignType` then appears in a descriptor of a class defined by the mock's loader, and that loader can't see it. So the mock genuinely needs reach that the real subclass doesn't.

But your objection still lands on my patch as written. `appendMostSpecific` only keeps both loaders when neither is reachable from the other, which in practice means sibling bundles — and that's exactly the case here, so the mock does end up in a synthetic loader and does lose package-private access.

Would a narrower version be worth it: define the mock with the current loader as today, and only fall back to a multi-parent loader if that fails? Nothing that works today would change, and the sibling-bundle case would stop being a hard `NoClassDefFoundError`. If you'd rather not carry the extra path, I'm fine closing this.

**Comment by Develop-KIM** [comment]
Closing this one. I'm winding down my open PRs and won't be around to follow up on the narrower fallback I floated. Your original point — that the multi-classloader lookup was dropped on purpose — still stands, so this is probably better left alone than half-changed. Thanks for the back and forth.
