### ISSUE TITLE
mockito-all includes org.hamcrest classes = bad practice

### ISSUE THREAD

**Issue by rop49** [mockito/mockito#324]
I just spent half a day+ tracing down a classloading failure...

java.lang.NoSuchMethodError: org.hamcrest.CoreMatchers.everyItem(Lorg/hamcrest/Matcher;)Lorg/hamcrest/Matcher;
	at org.junit.Assume.assumeNotNull(Assume.java:73)

Finally, I found the root-cause was that mockito-all-1.10.19 includes org.hamcrest* classes.
I don't know which hamcrest-version, but obviously older than current hamcrest-1.3.

I dont even use neither mockito nor hamcrest in this project (got both as transitive dependencies), 
and the gradle-build failed because mockito-all jar apparently happened to come before hamcrest on the classpath.

Very bad practice to include copies of classes from a different jar-dependency.

org.hamcrest classes should be removed from mockito-all, 
and instead specify hamcrest as a jar-dependency.

**Comment by szpak** [comment]
mockito-all is problematic and shouldn't be used in project with a dependency management tool (like Gradle/Maven/Ivy):
https://solidsoft.wordpress.com/2012/09/11/beyond-the-mockito-refcard-part-3-mockito-core-vs-mockito-all-in-mavengradle-based-projects/
(in Gradle you can exclude it or write a resolution strategy to automatically replace all transitive mockito-all with mockito-core)

However, mockito-all is deprecated and is no longer published starting with version 2.0.3-beta to not confuse users.

**Comment by jpsw** [comment]
OK, thanks for clarification.
And good to hear this toxic artifact is no longer published :)

**Comment by bric3** [comment]
@rop49 yes we know, this artifact was published for the reasons that @szpak mentioned.

For reference to what @szpak said, mockito-all is not anymore generated since this commit : d34597c33d3a5a3971ff1db68ef1cb8a1145ac03
