### ISSUE TITLE
Help in people migrating from one version to the next

### ISSUE THREAD

**Issue by paulduffin** [mockito/mockito#992]
After having gone through the process of migrating a reasonably sized body of code from 1.10.19 to 2.7.13 I thought it would be helpful to provide some feedback.

The way that I work is generally upgrade the code in question, in this case mockito, and then:

1. Build the code
1. Fix build failures
1. Repeat from step 1 until build works.

While this is an effective, albeit time consuming and tedious, process it can often be difficult to know what to use when something breaks. It also does not help when there are behavioral changes that need to be checked manually by the developer. e.g. The change to anyX() and any(SomeType.class) matchers to not accept null would not cause compilation errors, may not even cause tests to fail but could still cause some tests to be incorrect.

What would be absolutely awesome is if as you were developing you built up a library of [error prone checks](http://errorprone.info/docs/installation) that could be used by developers to not only identify the code that would be affected by the upgrade but in some cases thanks to [error prone's patching](http://errorprone.info/docs/patching) capabilities and [refaster rules](http://errorprone.info/docs/refaster) could actually fix the code for them as well.

One thing that I find really essential when doing the upgrade is to try and keep the changes to our code separate from the actual changes to the code we're upgrading. e.g. Where necessary when upgrading from 1.10.19 to 2.x I backported some changes from 2.x (e.g. MockitoHamcrest) to allow me to change our code to use the new 2.x way of doing things (e.g. handling hamcrest based matchers) before I actually upgraded.

Where that was not possible, e.g. with the changes to ArgumentMatcher, I created special compatibility classes in 1.10.19 that I changed the code to use and then added equivalent classes in 2.7.13 so that the code would continue to compile against it. Once the upgrade was completed the code was changed again to use standard 2.7.13 code.

I went from 1.10.19 to 2.7.13 rather than smaller increments mainly because the overhead of doing the upgrade was so high that it was not worth doing it in smaller steps. That is also why we delayed doing the upgrade for as long as we did which necessitated us making a big jump. I believe that using error prone can reduce the cost and risk of the upgrade to the point where developers can start doing it so regularly that they are never more than a few releases behind head.

If the cost of upgrade was trivial and you followed the principle that you must deprecate and provide a replacement in at least one version before you remove or change an API element then it would not be necessary to create special compatibility classes as you could just upgrade from one release to the next to the next.

Writing and testing the checkers and the refaster rules will take some time but they will bring huge benefits to users and also to you. After all if the cost of upgrading was low then you can contemplate making improvements that you would otherwise avoid due to the impact on developers.

I am quite happy to help and I know that the error prone developers would be interested in someone from outside Google using error prone like this.

**Comment by TimvdLippe** [comment]
This is a very nice concept, but I personally have absolutely zero experience with the tool nor with such big upgrades :stuck_out_tongue: 

Especially while working on a new API which would probably deprecate an old API, these refactor rules would be very welcome. My current approach would to write a regex that would do the refactor, but using refaster it seems more typesafe.

To be very honest: I am not sure how we can progress forward in this direction and it sounds like you are a lot more knowledgeable :smile: Should we publish a new project with these rules? I suppose these should not ship in the core library, but some sort of separate package. Or do we only supply snippets which the user has to copy-paste themselves?

Thank you for your interest in Mockito. If you have any direct commit you can link here to show what changes were required for Mockito 2.x, could you post it here?

**Comment by szczepiq** [comment]
@paulduffin, thank you very much for really thoughtful feedback and the links to the super useful tools. Out of curiosity, can you share what company you were upgrading Mockito?

I will be very happy to research those tools and see how applicable they are to future migrations.

>The change to anyX() and any(SomeType.class) matchers to not accept null would not cause compilation errors, may not even cause tests to fail but could still cause some tests to be incorrect.

Why would this change make the test incorrect? Most users who voted for this change claimed that it would actually flesh out incorrect tests and force developers to fix them. The change to anyX() makes the assertion _stricter_ so in theory it shouldn't make the test incorrect.

>If the cost of upgrade was trivial and you followed the principle that you must deprecate and provide a replacement in at least one version before you remove or change an API element

Absolutely agree! With anyX() it was hard to deprecate existing behavior because we wanted to correct that behavior. We liked the anyX() matcher and we didn't want to remove it.

THANK YOU for making the effort to migrate to newer version of Mockito!!!

**Comment by paulduffin** [comment]
I work for Google in the Android core library teams. I upgraded Mockito in AOSP and am now looking at internal Google code.

Tests that previously used anyX()/any(Class) because it did not care what values were passed to those arguments AND who actually pass null to those arguments will now fail. When that happens it can be difficult to determine what is the cause.

If the 'no longer matchers null' matcher is being used during verification then the error message is usually quite helpful, as it will say something like 'passed null, expected <any string>'.

If the matchers are being used when setting expectations and return values on a mock then because the expectation no longer matches the mock will return a different value which could cause the test to fail in many different ways. Debugging exactly what has gone wrong is very time consuming.

**Comment by TimvdLippe** [comment]
@paulduffin It has been a while, have you been able to progress on the Mockito integration? Is there work we can do to speed up the process if you were unable to finish the migration yet?

**Comment by paulduffin** [comment]
I had to leave the mockito work for a while but am back looking at it, albeit not full time. I am currently migrating code from 1.9.5 to 1.10.19.

**Comment by TimvdLippe** [comment]
I will work on this as part of my work on upgrading Mockito in Google. For future breaking changes, we must include the migration path and preferably included automated scripts (using ErrorProne). Sorry that we did not get to this sooner and that we make hard-to-migrate-from breaking changes in the past.
