### ISSUE TITLE
java.lang.NoClassDefFoundError in 3.5.0 (but works in 3.4.8)

### ISSUE THREAD

**Issue by hoisie** [mockito/mockito#2025]
Hi Mockito team,

This is a follow-up to https://github.com/mockito/mockito/issues/2015.

After https://github.com/mockito/mockito/issues/2015 was resolved with a combination of https://github.com/mockito/mockito/pull/2017 and https://github.com/robolectric/robolectric/pull/5875, I am seeing a (perhaps related?) error when running Mockito under a Robolectric environment.

There's a [simple test](https://github.com/hoisie/robolectric/blob/mockito-issue/integration_tests/mockito-experimental/src/test/java/org/robolectric/integrationtests/mockito/experimental/MockitoMockFinalsTest.java) in the robolectric repo that passes with mockito-inline 3.4.8 but fails with mockito-inline 3.5.0. After performing a git bisect, the culprit appears to be this commit: https://github.com/mockito/mockito/pull/2004/commits/106ebcfac809c578b128cf909e7f3f344f87ee69 (`Add support for creating constructors without using Objenesis (and unsafe API)`)

The test is very simple, it's just trying to mock an android.view.TextView object, which is a class that is instrumented by Roboletric:

```java
  @Rule public MockitoRule mockitoRule = MockitoJUnit.rule();

  @Mock TextView textView;
```

To repro:

```sh
git clone -b mockito-issue https://github.com/hoisie/robolectric
./gradlew :integration_tests:mockito-experimental:test

```
And the exception is:

```
java.lang.NoClassDefFoundError: Could not initialize class android.widget.TextView
	at jdk.internal.reflect.GeneratedSerializationConstructorAccessor11.newInstance(Unknown Source)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.objenesis.instantiator.sun.SunReflectionFactoryInstantiator.newInstance(SunReflectionFactoryInstantiator.java:48)
	at org.objenesis.ObjenesisBase.newInstance(ObjenesisBase.java:73)
	at org.mockito.internal.creation.instance.ObjenesisInstantiator.newInstance(ObjenesisInstantiator.java:21)
	at org.mockito.internal.creation.bytebuddy.InlineByteBuddyMockMaker.doCreateMock(InlineByteBuddyMockMaker.java:331)
	at org.mockito.internal.creation.bytebuddy.InlineByteBuddyMockMaker.createMock(InlineByteBuddyMockMaker.java:297)
	at org.mockito.internal.util.MockUtil.createMock(MockUtil.java:52)
	at org.mockito.internal.MockitoCore.mock(MockitoCore.java:61)
	at org.mockito.Mockito.mock(Mockito.java:1949)
	at org.mockito.internal.configuration.MockAnnotationProcessor.processAnnotationForMock(MockAnnotationProcessor.java:66)
	at org.mockito.internal.configuration.MockAnnotationProcessor.process(MockAnnotationProcessor.java:27)
	at org.mockito.internal.configuration.MockAnnotationProcessor.process(MockAnnotationProcessor.java:24)
	at org.mockito.internal.configuration.IndependentAnnotationEngine.createMockFor(IndependentAnnotationEngine.java:46)
	at org.mockito.internal.configuration.IndependentAnnotationEngine.process(IndependentAnnotationEngine.java:73)
	at org.mockito.internal.configuration.InjectingAnnotationEngine.processIndependentAnnotations(InjectingAnnotationEngine.java:73)
	at org.mockito.internal.configuration.InjectingAnnotationEngine.process(InjectingAnnotationEngine.java:47)
	at org.mockito.MockitoAnnotations.openMocks(MockitoAnnotations.java:82)
	at org.mockito.internal.framework.DefaultMockitoSession.<init>(DefaultMockitoSession.java:43)
	at org.mockito.internal.session.DefaultMockitoSessionBuilder.startMocking(DefaultMockitoSessionBuilder.java:83)
	at org.mockito.internal.junit.JUnitSessionStore$1.evaluate(JUnitSessionStore.java:37)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:575)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:263)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

I am not sure if this is an issue with Mockito or Robolectric or both, but I'd be happy to help in any way.

**Comment by raphw** [comment]
We updated Objenesis. Could you manually downgrade to 2.6 with the latest Mockito to see if that's the issue?

**Comment by hoisie** [comment]
Sure, I'll try downgrading Objenesis real quick.

Another weird thing is that if I comment out the logic in `InlineByteBuddyMockMaker.java` that attempts to use the native mock maker:

```
                // try {
                //     // We attempt to use the "native" mock maker first that avoids
                //     // Objenesis and Unsafe
                //     instance = newInstance(type);
                // } catch (InstantiationException ignored) {
                //     if (nullOnNonInlineConstruction) {
                //         return null;
                //     }
                    Instantiator instantiator =
                            Plugins.getInstantiatorProvider().getInstantiator(settings);
                    instance = instantiator.newInstance(type);
                // }
```

the test starts passing again.

**Comment by raphw** [comment]
That is weird since the exception does not occur in that outcommented part but in the lines benetg.

**Comment by hoisie** [comment]
Actually nevermind, that test passes in 3.5.8. So something between 3.5.4 and 3.5.8 fixed the issue. SFTN. 3.5.8 works regardless of Objenesis version.

**Comment by hoisie** [comment]
Did another inverse bisect and this issue was fixed in 24d8d790c22913a9a92ea70bad721b06a735cd46. That's great! Closing this now.
