### PR TITLE
Upgrade to Gradle 3.0

### LINKED ISSUE #521: Remove com.sun.* references
Currently build with gradle 3.0-milestone-2 fails with:

```
:buildSrc:compileJava/mnt/homeold/szpak/cosie/code/inne/mockito/buildSrc/src/main/java/org/mockito/javadoc/JavadocExclude.java:4: error: package com.sun.tools.doclets.formats.html does not exist
import com.sun.tools.doclets.formats.html.HtmlDoclet;
                                         ^
/mnt/homeold/szpak/cosie/code/inne/mockito/buildSrc/src/main/java/org/mockito/javadoc/JavadocExclude.java:20: error: cannot find symbol
        return HtmlDoclet.optionLength(var0);
               ^
  symbol:   variable HtmlDoclet
  location: class JavadocExclude
/mnt/homeold/szpak/cosie/code/inne/mockito/buildSrc/src/main/java/org/mockito/javadoc/JavadocExclude.java:25: error: cannot find symbol
        return HtmlDoclet.start((RootDoc) Proxy.newProxyInstance(clz.getClassLoader(), clz.getInterfaces(), new ExcludeHandler(root)));
               ^
  symbol:   variable HtmlDoclet
  location: class JavadocExclude
/mnt/homeold/szpak/cosie/code/inne/mockito/buildSrc/src/main/java/org/mockito/javadoc/JavadocExclude.java:29: error: cannot find symbol
        return HtmlDoclet.validOptions(var0, var1);
               ^
  symbol:   variable HtmlDoclet
  location: class JavadocExclude
/mnt/homeold/szpak/cosie/code/inne/mockito/buildSrc/src/main/java/org/mockito/javadoc/JavadocExclude.java:33: error: cannot find symbol
        return HtmlDoclet.languageVersion();
               ^
  symbol:   variable HtmlDoclet
  location: class JavadocExclude
Note: /mnt/homeold/szpak/cosie/code/inne/mockito/buildSrc/src/main/java/org/mockito/javadoc/JavadocExclude.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
5 errors
 FAILED
```

Related to #520.

### LINKED ISSUE #561: Update Gradle to 3.0
Gradle 3.0 is released so we can look into upgrading. Potentially we can rewrite our scripts into Kotlin.

### PR DESCRIPTION
**Pull request by TimvdLippe**
This bumps Gradle to 3.0. I was unable to reproduce the issue reported by @szpak in #521 about a failing compilation locally. Maybe Gradle fixed this after the release candidate was published which was originally used in #521.

Fixes #561 
Closes #521

### CODE REVIEW

File: gradle/javadoc.gradle [hunk 1]
```diff
@@ -54,9 +54,7 @@ task mockitoJavadoc(type: Javadoc) {
     """.replaceAll(/\r|\n/, ""))
     options.stylesheetFile file("src/javadoc/stylesheet.css")
 //    options.addStringOption('top', 'some html')
-    if (JavaVersion.current().isJava8Compatible()) {
-        options.addStringOption('Xdoclint:none', '-quiet')
-    }
+    options.addStringOption('Xdoclint:none', '-quiet')
```
Comment (szczepiq) [inline gradle/javadoc.gradle]: I assume we already moved the baseline java8 so this should be safe. Nice.

Comment (TimvdLippe) [inline gradle/javadoc.gradle]: Yup in https://github.com/mockito/mockito/commit/be755a3d9e8424e8587857390abbc07001644778 :smile:

**Comment by szpak** [comment]
I was building it with Java 9 what caused a compilation failure.
