### ISSUE TITLE
Remove com.sun.* references

### ISSUE THREAD

**Issue by szpak** [mockito/mockito#521]
Currently build with gradle 3.0-milestone-2 fails with:

```
:buildSrc:compileJava/mnt/homeold/szpak/cosie/code/inne/mockito/buildSrc/src/main/java/org/mockito/javadoc/JavadocExclude.java:4: error: package com.sun.tools.doclets.formats.html does not exist
import com.sun.tools.doclets.formats.html.HtmlDoclet;
                                         ^
/mnt/homeold/szpak/cosie/code/inne/mockito/buildSrc/src/main/java/org/mockito/javadoc/JavadocExclude.java:20: error: cannot find symbol
        return HtmlDoclet.optionLength(var0);
               ^
  symbol:   variable HtmlDoclet
  location: class JavadocExclude
/mnt/homeold/szpak/cosie/code/inne/mockito/buildSrc/src/main/java/org/mockito/javadoc/JavadocExclude.java:25: error: cannot find symbol
        return HtmlDoclet.start((RootDoc) Proxy.newProxyInstance(clz.getClassLoader(), clz.getInterfaces(), new ExcludeHandler(root)));
               ^
  symbol:   variable HtmlDoclet
  location: class JavadocExclude
/mnt/homeold/szpak/cosie/code/inne/mockito/buildSrc/src/main/java/org/mockito/javadoc/JavadocExclude.java:29: error: cannot find symbol
        return HtmlDoclet.validOptions(var0, var1);
               ^
  symbol:   variable HtmlDoclet
  location: class JavadocExclude
/mnt/homeold/szpak/cosie/code/inne/mockito/buildSrc/src/main/java/org/mockito/javadoc/JavadocExclude.java:33: error: cannot find symbol
        return HtmlDoclet.languageVersion();
               ^
  symbol:   variable HtmlDoclet
  location: class JavadocExclude
Note: /mnt/homeold/szpak/cosie/code/inne/mockito/buildSrc/src/main/java/org/mockito/javadoc/JavadocExclude.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
5 errors
 FAILED
```

Related to #520.

**Comment by TimvdLippe** [comment]
This doclet is required to skip generating Javadoc for internal classes. Is there a mention in the Java 9 jdk of this breaking change?

**Comment by TimvdLippe** [comment]
This seems the corresponding JIRA ticket: https://bugs.openjdk.java.net/browse/JDK-8154399

**Comment by bric3** [comment]
I'm on a mobile device so couldn't check much, but the ticket mention a replacement for `com.sun....Standard` with the rewritten javadoc tool (`jdk.javadoc.doclets.StandardDoclet`) I didn't saw yet the `HtmlDocklet` yet it should be there as well.

**Comment by TimvdLippe** [comment]
I will be taking a stab at this tomorrow after switching to Java 8.

**Comment by TimvdLippe** [comment]
I think we have to (in jdk9) to move to `StandardDoclet`: http://hg.openjdk.java.net/jdk9/dev/langtools/file/6077dc32728a/src/jdk.javadoc/share/classes/jdk/javadoc/doclets/StandardDoclet.java However, this class does not exist in jdk8 so I am not sure what our options are.

**Comment by bric3** [comment]
I think we could have both doclet in [javadoc.gradle](https://www.theguardian.com/lifeandstyle/2016/apr/29/how-to-have-a-great-conversation-with-someone-who-is-going-to-die)

```java
if (JavaVersion.current().isJava9Compatible()) {
    options.doclet "org.mockito.javadoc.Java9JavadocExclude"
} else {
    options.doclet "org.mockito.javadoc.JavadocExclude"
}
```


[`JavaVersion` javadoc](https://docs.gradle.org/current/javadoc/org/gradle/api/JavaVersion.html)

**Comment by TimvdLippe** [comment]
@bric3 Yes that was what I implemented at https://github.com/mockito/mockito/pull/639/files#diff-39cbd22b5198600bd49c364c42e0aaa9R17 :)
