### PR TITLE
Retry subclass mock creation with superclass loaders on NoClassDefFoundError

### LINKED ISSUE #2694: java.lang.NoClassDefFoundError with mockito 3.11+
Hi, we found following issue in our projects after updating mockito from 3.6 to 4.3.

Example: We have four different Java classes in four different OSGi plug-ins. In OSGi, each plug-ins has its own classloader.

Plug-in 1 contains the interface:

`public interface IDummyObject { }`

Plug-in 2 contains an implementation and has a dependency, e.g. here to org.eclipse.emf.ecore:

```
import org.eclipse.emf.ecore.EObject;

import dummyInterfaces.IDummyObject;

public class DummyObject implements IDummyObject {
  EObject _obj;
}
```

Plug-in 3 contains an other implementation, here it is a subclass of DummyObject and implemented as a component. The plug-in has no dependency to org.eclipse.emf.ecore:

```
import org.osgi.service.component.annotations.Component;

import dummyInterfaces.IDummyObject;

@Component
public class ExtendedDummyObject extends DummyObject implements IDummyObject {

}
```

Plug-In 4 contains a test using a spy on the injected dummy object:

```
import static org.mockito.Mockito.spy;

import javax.inject.Inject;

import org.junit.jupiter.api.Test;

import dummyInterfaces.IDummyObject;
import vi.testfw.ITest;

public class DummyObjectTest implements ITest {

  @Inject
  private IDummyObject _dummyObject;

  @Test
  void testSomething() {
    spy(_dummyObject);
  }

}
```

With the update from mockito 3.10 to 3.11 following change was comitted: [https://github.com/mockito/mockito/commit/66998ea7f81c6adf49983cea081586e19760b7a0](https://github.com/mockito/mockito/commit/66998ea7f81c6adf49983cea081586e19760b7a0), containing following change: `.appendMostSpecific(getAllTypes(features.mockedType))` changed to `.appendMostSpecific(features.mockedType)
`

Scenario above used to work before. Also the commit message says "This should **only** affect cases that previously would have thrown an exception." However, with this commit the classloader of the superclass DummyObject is not fetched anymore, only the classloaders for the interface IDummyObject and the ExtendedDummyObject, leading to following exception:

```
java.lang.NoClassDefFoundError: org/eclipse/emf/ecore/EObject
	at org.mockito.codegen.ExtendedDummyObject$MockitoMock$91908986.<clinit>(Unknown Source)
	at jdk.internal.reflect.GeneratedSerializationConstructorAccessor10.newInstance(Unknown Source)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.objenesis.instantiator.sun.SunReflectionFactoryInstantiator.newInstance(SunReflectionFactoryInstantiator.java:48)
	at org.objenesis.ObjenesisBase.newInstance(ObjenesisBase.java:73)
	at org.mockito.internal.creation.instance.ObjenesisInstantiator.newInstance(ObjenesisInstantiator.java:22)
	at org.mockito.internal.creation.bytebuddy.SubclassByteBuddyMockMaker.createMock(SubclassByteBuddyMockMaker.java:48)
	at org.mockito.internal.creation.bytebuddy.ByteBuddyMockMaker.createMock(ByteBuddyMockMaker.java:42)
	at org.mockito.internal.util.MockUtil.lambda$createMock$0(MockUtil.java:48)
	at java.base/java.util.Optional.orElseGet(Optional.java:369)
	at org.mockito.internal.util.MockUtil.createMock(MockUtil.java:46)
	at org.mockito.internal.MockitoCore.mock(MockitoCore.java:96)
	at org.mockito.Mockito.spy(Mockito.java:2048)
	at dummyPackage.DummyObjectTest.setUp(DummyObjectTest.java:26)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:725)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.api.extension.InvocationInterceptor.interceptBeforeEachMethod(InvocationInterceptor.java:103)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptLifecycleMethod(TimeoutExtension.java:126)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptBeforeEachMethod(TimeoutExtension.java:76)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeMethodInExtensionContext(ClassBasedTestDescriptor.java:506)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$synthesizeBeforeEachMethodAdapter$21(ClassBasedTestDescriptor.java:491)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeBeforeEachMethods$3(TestMethodTestDescriptor.java:171)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeBeforeMethodsOrCallbacksUntilExceptionOccurs$6(TestMethodTestDescriptor.java:199)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeBeforeMethodsOrCallbacksUntilExceptionOccurs(TestMethodTestDescriptor.java:199)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeBeforeEachMethods(TestMethodTestDescriptor.java:168)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:131)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:66)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:107)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:95)
	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:91)
	at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:60)
	at org.eclipse.jdt.internal.junit5.runner.JUnit5TestReference.run(JUnit5TestReference.java:98)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:542)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:770)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:464)
	at org.eclipse.pde.internal.junit.runtime.RemotePluginTestRunner.main(RemotePluginTestRunner.java:171)
	at org.eclipse.pde.internal.junit.runtime.CoreTestApplication.run(CoreTestApplication.java:27)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.internal.app.EclipseAppContainer.callMethodWithException(EclipseAppContainer.java:593)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:205)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:657)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:594)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1457)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1420)
Caused by: java.lang.ClassNotFoundException: org.eclipse.emf.ecore.EObject
	at java.base/java.lang.ClassLoader.findClass(ClassLoader.java:719)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at net.bytebuddy.dynamic.loading.MultipleParentClassLoader.loadClass(MultipleParentClassLoader.java:131)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 110 more
```

### PR DESCRIPTION
**Pull request by Dextheking1**
Fixes #2694

In OSGi environments, mocking a class whose superclass is defined by another bundle fails with `NoClassDefFoundError` when the superclass references types that the mock's class loader cannot see. Since the generated mock redeclares inherited methods, those types must be resolvable by the mock's loader.

This adds a fallback: if mock creation throws `NoClassDefFoundError`, retry once with the superclass loaders included in the mock's class loader via `MultipleParentClassLoader.Builder.appendMostSpecific`.

The default strategy is always tried first and is completely unchanged, so ordinary usage is unaffected. The fallback is skipped when no superclass has a distinct class loader. A separate bytecode generator (and cache) is used for the fallback so the default path's cache is never contaminated.

Added an OSGi regression test (`MockSubclassWithForeignSuperclassTest`) with a three-bundle topology: the test bundle mocks a subclass whose superclass (from another bundle) references a type the test bundle cannot see.

---
*This PR was prepared with AI assistance; I have reviewed and understand the changes.*

### CODE REVIEW

**Comment by raphw** [comment]
Admittedly, I am not a fan of a silent fallback. It is already possible to adjust the mock engine per mock. If this is common, I would suggest to override the global engine as with OSGi. Would that not be more feasible?

**Comment by Dextheking1** [comment]
Thanks for the feedback, and fair point on silent fallbacks. Let me explain why I reached for the in-maker retry, and then I am happy to reshape it however you prefer.

The failure this fixes (mockito/mockito#2694) is environment-dependent and opaque to the user: in OSGi the mock of a subclass blows up with a NoClassDefFoundError for a type the user never referenced directly (it comes from a superclass in another bundle), with nothing pointing at the mock engine as the culprit. Requiring every affected user to discover the MockMaker plugin mechanism, write a wrapper engine, and register it via mockito-extensions felt like pushing framework internals onto them, when the framework itself knows exactly what went wrong: the mock's loader cannot see the superclass's loader. The retry is also deliberately narrow: the default strategy is always tried first and is unchanged, the retry fires only on NoClassDefFoundError, it is skipped when no superclass has a distinct loader (so it cannot mask unrelated linkage errors), and it runs through a separate generator/cache so the default path is never contaminated.

That said, I agree nothing should happen silently. Two alternatives:

1. Keep the retry in the maker but make it opt-in via a MockSettings flag, so users in OSGi-style environments enable it explicitly and default behavior is byte-for-byte what it is today.
2. Drop the in-maker retry and instead provide/document a global engine override (a mockito-extensions MockMaker wrapping the default maker with this retry) that users enable once.

Which direction would you prefer? I can rework the PR accordingly.

**Comment by raphw** [comment]
You could create a fallback mock maker in this case and delegate to those shipped by Mockito?

**Comment by Dextheking1** [comment]
Good idea, that lines up with option 2. I will reshape it as a standalone fallback MockMaker in mockito-core that delegates to the shipped subclass maker and retries with the superclass loaders on NoClassDefFoundError, enabled through mockito-extensions. The in-maker retry goes away and the OSGi test moves to the new maker. Say the word if you had different wiring in mind.
