### ISSUE TITLE
Capturing vararg arguments in Kotlin is broken after updating from 4.9.0 to 5.1.1

### ISSUE THREAD

**Issue by bacecek** [mockito/mockito#2914]
Let's assume we have mocked class that has method with vararg argument:

```
open class Logger {

    open fun logg(vararg args: String) {
        val msg = args.joinToString()
        println(msg)
    }
}
```

And other class, that uses the class above:
```
class Sample(private val logger: Logger) {

    fun test() {
        logger.logg("test", "test2")
    }
}
```

The following test is passing with 4.9.0 version and failing with 5.1.0:
```
class SampleMockTest {

    @Test
    fun testVararg() {
        val mssgs = argumentCaptor<String>()
        val logger = mock<Logger> {
            on { logg(mssgs.capture()) } doAnswer {}
        }
        val sample = Sample(logger)
        sample.test()
        assertEquals(2, mssgs.allValues.size)
    }
}
```

I can't use array in `ArgumentCaptor` declaration like this: `val mssgs = argumentCaptor<Array<String>>()` because I'm getting the compilation error:
```
Type mismatch: inferred type is Array<String> but String was expected
```
Also I've tried this:
```
        val mssgs = argumentCaptor<Array<String>>()
        val logger = mock<Logger> {
            on { logg(*mssgs.capture()) } doAnswer {}
        }
```
<details><summary>But I'm getting NPE:</summary>

```
NullPointerException thrown when stubbing.
This may be due to two reasons:
	- The method you're trying to stub threw an NPE: look at the stack trace below;
	- You're trying to stub a generic method: try `onGeneric` instead.
org.mockito.kotlin.MockitoKotlinException: NullPointerException thrown when stubbing.
This may be due to two reasons:
	- The method you're trying to stub threw an NPE: look at the stack trace below;
	- You're trying to stub a generic method: try `onGeneric` instead.
	at app//org.mockito.kotlin.KStubbing.on(KStubbing.kt:72)
	at app//SampleMockTest.testVararg(SampleMockTest.kt:13)
	at java.base@11.0.17/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base@11.0.17/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base@11.0.17/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base@11.0.17/java.lang.reflect.Method.invoke(Method.java:566)
	at app//org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at app//org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at app//org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at app//org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at app//org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at app//org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at app//org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at app//org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at app//org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at app//org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at app//org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at app//org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at app//org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at app//org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at app//org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at app//org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:108)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:57)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:39)
	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:52)
	at java.base@11.0.17/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base@11.0.17/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base@11.0.17/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base@11.0.17/java.lang.reflect.Method.invoke(Method.java:566)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker$2.run(TestWorker.java:176)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
	at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:113)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:65)
	at app//worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
	at app//worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)
Caused by: java.lang.NullPointerException
	at SampleMockTest$testVararg$logger$1$1.invoke(SampleMockTest.kt:13)
	at SampleMockTest$testVararg$logger$1$1.invoke(SampleMockTest.kt:13)
	at org.mockito.kotlin.KStubbing.on(KStubbing.kt:70)
	... 44 more

```

</details>

Java version:
```
openjdk 11.0.17 2022-10-18
OpenJDK Runtime Environment Temurin-11.0.17+8 (build 11.0.17+8)
OpenJDK 64-Bit Server VM Temurin-11.0.17+8 (build 11.0.17+8, mixed mode)
```
Mockito Kotlin version: 4.1.0.

Whole example test to reproduce:
https://github.com/bacecek/sample-checking-assistant-role/blob/mockito_5_argumentCaptor_kotlin/app/src/test/java/SampleMockTest.kt

**Comment by TimvdLippe** [comment]
Duplicate of https://github.com/mockito/mockito-kotlin/issues/474
