### ISSUE TITLE
There is a issue, after I downgrade the Mockito version, it disappeared

### ISSUE THREAD

**Issue by eetech** [mockito/mockito#1207]
Hi guys, I found an issue, when I try to mock Realm with Mockito 2.10.0 and PowerMock 1.7.0RC4 , I get an error:
```
java.lang.NoSuchMethodError: org.mockito.internal.handler.MockHandlerFactory.createMockHandler(Lorg/mockito/mock/MockCreationSettings;)Lorg/mockito/internal/InternalMockHandler;
```
then I downgrade Mockito to 2.8.47(I tried that it works well on <= 2.8.47), the error disappeared, so I just wondering is it a bug in new versions? Thanks ;-)

**Comment by TimvdLippe** [comment]
This is probably related to a corrupt `.m2` cache. Could you delete any local versions of Mockito and try again?

**Comment by TimvdLippe** [comment]
Depending on your operating system, it is probably located in your home folder. In my case it is `ls ~/.m2/repository/org/mockito/` on Ubuntu. Go to your home folder and search for `.m2`

**Comment by eetech** [comment]
there is the folder ` ~/.m/r/org`, but no `mockito` there... @TimvdLippe

**Comment by TimvdLippe** [comment]
So if that is the case, then one of your other dependencies was relying on an internal API that was removed between these versions. It could be that `PowerMock` is the culprit, but I am not certain about that. PowerMock should be using only public API in the latest version, so maybe try that out and see if it makes it compile again?

**Comment by eetech** [comment]
@TimvdLippe When I upgraded PowerMock to 1.7.3, I got another PowerMock error, so only Mockito 2.8.47 & PowerMock 1.7.0RC4 works well. so I'm not sure why it couldn't work on latest version, and I didn't know what has been changed between the older version and latest version

**Comment by mockitoguy** [comment]
Sorry for the issue!

Please report it to PowerMock tracker. Mockito team does not support PowerMock integration.

The only way Mockito team can help Java developers for this use case is by providing comprehensive public API for framework integrations. This way, PowerMock can cleanly integrate with Mockito public API and avoid various method not found errors. We have [added new public API](https://www.linkedin.com/pulse/test-tools-creator-dilemma-szczepan-faber/) in Mockito 2.10.0, now PowerMock needs to release a new version with this API.

Hope that helps clarifying the use case!

**Comment by tkruse** [comment]
Reported to Powermock, they suggest to try PowerMock2 Beta


https://github.com/powermock/powermock/issues/867

**Comment by eetech** [comment]
Thanks guys

**Comment by kwilliams3** [comment]
Confirmed, upgrading to `2.0.0-beta.5` does solve the problem. I had to do this for both `powermock-api-mockito2` and `powermock-module-junit4`

**Comment by goxr3plus** [comment]
@kwilliams3  You comment saved me just now.
